const AppUser = require('../../models/app_user')
const Quest = require('../../models/quest')

const authenticate = async (token) => {
    let user
    if (token === 'admin') {
        user = {
            "quests": [],
            "_id": "5a85756ef41b1a447acce08a",
            "username": "hunter",
            "email": "gyxgyx@helsinki.fi",
            "tmc_id": 25936,
            "admin": true,
            "points": 0,
            "__v": 4
        }
    } else if (token.includes('hasQuestStarted')) {
        //Because this module has to return user that is saved to mongo, we need to add the already defined and "started" quest to user
        //and we need to update the same quest in database with new user id that is generated in the process.

        //1st: send quest id with token that includes string "hasQuestStarted" and add quest id to user
        user = {
            "id": '5a85756ef41b1a447acce08a',
            "tmc_id": 25936,
            "username": 'hunter',
            "points": 0,
            "email": 'gyxgyx@helsinki.fi',
            "admin": false,
            "quests":
                [{
                    _id: '5a981abbabd1a43cd4055f7b',
                    quest: token.substring(16),
                    startTime: '2018-03-01T15:22:35.445Z',
                    finishTime: null
                }]
        }

        //2nd: save the new user with correct quest id to test database
        const newUser = new AppUser(user)

        //3rd: update the quest to have the new user id generated by mongo
        await Quest.findByIdAndUpdate(token.substring(16),
            {   
                usersStarted: [{
                    _id: "5a981abbabd1a43cd4055f7c",
                    user: newUser._id,
                    startTime: "2018-03-01T15:22:35.445Z",
                    finishTime: null
                }]
            })

        return newUser

    } else {
        user = {
            "quests": [],
            "_id": "5a85756ef41b1a447acce08a",
            "username": "hunter",
            "email": "gyxgyx@helsinki.fi",
            "tmc_id": 25936,
            "admin": false,
            "points": 0,
            "__v": 4
        }
    }
    const newUser = new AppUser(user)
    return newUser
}

module.exports = { authenticate }