language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm test

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - "echo $TRAVIS_PULL_REQUEST"
  - "curl -o /tmp/travis-automerge https://raw.githubusercontent.com/OhtuHunt/HuntForGlory/travis-merge.sh"
  - "chmod a+x /tmp/travis-automerge"
  - "BRANCHES_TO_MERGE_REGEX='^devel' BRANCH_TO_MERGE_INTO=master GITHUB_REPO='Ouzii/OhtuMiniprojektiTeamPollot' /tmp/travis-automerge"


